### ISSUE TITLE
unexpected operator unrecognized option

### ISSUE THREAD

**Issue by tiagofreire-pt** [rickycodes/pve-no-subscription#4]
On Proxmox 7.2-1, the script crashes:

```
 curl --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/rickycodes/pve-no-subscription/main/no-subscription-warning.sh | sh      attempting pve-no-subscription patch                                                            status => "NotFound",                                           sh: 53: [: unexpected operator                                                  unrecognized option
```

Pve version:

pveversion -v                                                   proxmox-ve: 7.2-1 (running kernel: 5.15.30-2-pve)                               pve-manager: 7.2-3 (running version: 7.2-3/c743d6c1)                            pve-kernel-helper: 7.2-2                                                        pve-kernel-5.15: 7.2-1                                                          pve-kernel-5.13: 7.1-9                                                          pve-kernel-5.15.30-2-pve: 5.15.30-3                                             pve-kernel-5.13.19-6-pve: 5.13.19-15                                            pve-kernel-5.13.19-2-pve: 5.13.19-4                                             ceph-fuse: 15.2.15-pve1                                                         corosync: 3.1.5-pve2                                                            criu: 3.15-1+pve-1                                                              glusterfs-client: 9.2-1                                                         ifupdown2: 3.1.0-1+pmx3                                                         ksm-control-daemon: 1.4-1                                                       libjs-extjs: 7.0.0-1                                                            libknet1: 1.22-pve2                                                             libproxmox-acme-perl: 1.4.2                                                     libproxmox-backup-qemu0: 1.2.0-1                                                libpve-access-control: 7.1-8                                                    libpve-apiclient-perl: 3.2-1                                                    libpve-common-perl: 7.1-6                                                       libpve-guest-common-perl: 4.1-2                                                 libpve-http-server-perl: 4.1-1                                                  libpve-storage-perl: 7.2-2                                                      libspice-server1: 0.14.3-2.1                                                    lvm2: 2.03.11-2.1                                                               lxc-pve: 4.0.12-1                                                               lxcfs: 4.0.12-pve1                                                              novnc-pve: 1.3.0-3                                                              proxmox-backup-client: 2.1.8-1                                                  proxmox-backup-file-restore: 2.1.8-1                                            proxmox-mini-journalreader: 1.3-1                                               proxmox-widget-toolkit: 3.4-10                                                  pve-cluster: 7.2-1                                                              pve-container: 4.2-1                                                            pve-docs: 7.2-2                                                                 pve-edk2-firmware: 3.20210831-2                                                 pve-firewall: 4.2-5                                                             pve-firmware: 3.4-1                                                             pve-ha-manager: 3.3-4                                                           pve-i18n: 2.7-1                                                                 pve-qemu-kvm: 6.2.0-5                                                           pve-xtermjs: 4.16.0-1                                                           qemu-server: 7.2-2                                                              smartmontools: 7.2-pve3                                                         spiceterm: 3.2-2                                                                swtpm: 0.7.1~bpo11+1                                                            vncterm: 1.7-1                                                                  zfsutils-linux: 2.1.4-pve1

**Comment by ijaron** [comment]
Commenting out the following section of code seems to make the script work however without the --steamroll option
`#if ! [ "$ARG" == "--steamroll" ]; then`
`#  echo "unrecognized option"`
`#  exit 1`
`#fi`
